apiVersion: v1
kind: Namespace
metadata:
  name: gitops-with-tanzu
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: gitops-with-tanzu
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/repo"
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/alexandreroman/gitops-with-tanzu-repo:stable
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-with-tanzu-sa
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-with-tanzu-role
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-with-tanzu-role-binding
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
subjects:
- kind: ServiceAccount
  name: gitops-with-tanzu-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-with-tanzu-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-default-sa
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: core-default-role
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: core-default-role-binding
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
subjects:
- kind: ServiceAccount
  name: core-default-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: core-default-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-default-sa
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-default-role
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-default-role-binding
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/repo"
subjects:
- kind: ServiceAccount
  name: monitoring-default-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-default-role
