apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: hello-kubernetes
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/apps-hello-kubernetes"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting gitops-with-tanzu/core"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting gitops-with-tanzu/core"
spec:
  serviceAccountName: gitops-with-tanzu-sa
  fetch:
  - git:
      url: https://github.com/paulbouwer/hello-kubernetes
      ref: origin/main
      subPath: deploy/helm/hello-kubernetes
  template:
  - helmTemplate:
      namespace: hello-kubernetes
      valuesFrom:
      - secretRef:
          name: hello-kubernetes-values
  - ytt:
      inline:
        paths:
          fix-ns.yml: |
            #@ load("@ytt:overlay", "overlay")

            #@overlay/match by=overlay.subset({"metadata": {"labels": { "app.kubernetes.io/name": "hello-kubernetes"}}}),expects="1+"
            ---
            metadata:
              #@overlay/match missing_ok=True
              namespace: hello-kubernetes
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: hello-kubernetes
          add-ingress.yml: |
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: ingress
              namespace: hello-kubernetes
            spec:
              rules:
              - host: hello-kubernetes.10.213.73.23.nip.io
                http:
                  paths:
                  - pathType: ImplementationSpecific
                    path: /
                    backend:
                      service:
                        name: hello-kubernetes-hello-kubernetes
                        port:
                          number: 80
  - kbld:
      paths:
      - "-"
  deploy:
  - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-kubernetes-values
  namespace: gitops-with-tanzu
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/apps-hello-kubernetes"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting gitops-with-tanzu/rbac"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting gitops-with-tanzu/core"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting gitops-with-tanzu/core"
type: Opaque
stringData:
  data.yml: |
    ingress:
      configured: true
      pathPrefix: ""
    deployment:
      container:
        image:
          repository: ghcr.io/alexandreroman/hello-kubernetes
          tag: "1.10"
    service:
      type: ClusterIP
